/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    "intro",
    {
      type: "link",
      label: "Browse By Tag",
      href: "/docs/tags",
    },
    {
      type: "category",
      label: "Recipes",
      collapsed: false,
      items: [{ type: "autogenerated", dirName: "recipes" }],
    },
    {
      type: "category",
      label: "Archive",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "archive" }],
    },
  ],
};

module.exports = sidebars;
