name: Bug report
description: For issues with a recipe or the cookbook site
labels: ["bug"]
body:

  - type: markdown
    attributes:
      value: >
        Before creating a **bug report**, please check the following:
          * Ensure you're running the latest version release.
          * Ensure there isn't an existing issue for your bug. If there is, leave a comment on the existing issue.
        If you're unsure whether you've hit a bug, check out the #ignite channel in our [Slack Community](https://community.infinite.red).
  - type: textarea
    attributes:
      label: Describe the bug
      description: Also include a description of how to reproduce the bug
    validations:
      required: true
